#!/usr/bin/env ruby
require_relative '../../libs/simple_line_reader'
require_relative '../../libs/array_writer'
require_relative '../../libs/column'
require_relative '../../libs/column_def_parser'
require_relative '../../libs/fixed_width'

this_dir = File.dirname(__FILE__)
layout_file = File.join(this_dir, "example_layout.txt")
content_file = File.join(this_dir, "example_content.txt")
output_file = File.join(this_dir, "output.txt")
header_map = {name: "TEXT", start: "START", end: "END", length: "LEN", type: "TYPE", dec1: "DEC", dec2: "POS"}
reader = Converter::SimpleLineReader.new(content_file)
writer = Converter::ArrayWriter.new(output_file, "\t")
columns = Converter::ColumnDefParser.new(layout_file, header_map).parse
convert_options = {strip_content: true, skip_rows: 1, line_comment_markers: [";", "#"]}
fw = Converter::FixedWidth.new(reader, writer, columns, convert_options)
fw.convert
